### ISSUE TITLE
XMPP support?

### ISSUE THREAD

**Issue by poVoq** [sparky8251/matrix-bot#5]
https://gitlab.com/xmpp-rs/xmpp-rs

Could be used. Allways nice to have more options and XMPP where all the cool kids are :)

**Comment by sparky8251** [comment]
Currently, large portions of the codebase assume matrix will be the used protocol. From typing on various config fields (to ease config validation) to a matrix API client in the primary struct that makes this all work.

I'm not opposed to this in principle, but I'm not going to be the one that does it, and the method for doing it has to be as "seamless" as it can be.
