### ISSUE TITLE
[Feature Request] Arbitrary keyword responses

### ISSUE THREAD

**Issue by mcarlton00** [sparky8251/matrix-bot#9]
I want the bot to do my copy/paste for me so I don't have to keep finding where I stashed my source text at.

### Example:
**trigger text:**
`!addons`, `/kodi`, "something shorter than the below text, i don't care what"

**response text:**

* [Jellyfin for Kodi](https://github.com/jellyfin/jellyfin-kodi) - This addon syncs metadata from selected Jellyfin libraries into the local Kodi database. This has the effect of making interacting with it feel very much like vanilla Kodi with local media (shows up under Movies/TV Shows on the home screen by default, virtually no delay, etc). However, it also tends to consume the database and not share well, so if you have local media or something else that interacts with the database directly, you'll have conflicts and it won't be happy. The sync process can take some extra time on Kodi startup if you don't leave it running 24/7, but it's mostly in the background while Kodi is running.
* [JellyCon](https://github.com/jellyfin/jellycon) - Behaves more like a standard Kodi streaming addon. Media is accessed primarily by going through the Add-ons -> JellyCon menu, however you can set up menu options to link to it and show info on the home screen. It also allows easier switching between multiple Jellyfin servers or users since it doesn't have to rely on syncing all the metadata down. By not having metadata synced, it has to request info from the server which can take a bit more time when you're browsing (typically only a few seconds, but varies based on library size), but you don't have to wait for the database to sync or keep it up to date.

**Comment by sparky8251** [comment]
Implemented and deployed keyword text expansion with `$kodi` and $jellycon` to start with as requested. Can take others, just cannot contain `"` as that is used to block off the text in the config file.
